### ISSUE TITLE
Bug: gutil.log() ignores "gulp --silent"

### ISSUE THREAD

**Issue by bid** [gulpjs/gulp-util#68] opened 2014-10-08 21:13 UTC
See https://github.com/sindresorhus/gulp-imagemin/issues/69

The log() method needs to respect gulps "--silent" argument.

**Comment by stringparser** [comment] 2015-04-13 16:48
PR or is this stale/not needed anymore? This is would be an easy thing todo if is done globally.

**Comment by contra** [comment] 2015-04-14 02:39
Not needed anymore since we have a new logger inbound and gulp-util is deprecated

**Comment by stringparser** [comment] 2015-04-14 07:19
great

**Comment by phated** [comment] 2015-09-10 22:54
Closing as a duplicate of #33

**Closed by phated** 2015-09-10 22:54 UTC
Labels: bug, enhancement
